apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jenkins-server.fullname" . }}
data:
  installPlugin.sh: |-
    cp /var/jenkins_config/plugins.txt /var/jenkins_home;
    rm -rf /usr/share/jenkins/ref/plugins/*.lock
    version () { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }
    if [ -f "/usr/share/jenkins/jenkins.war" ] && [ -n "$(command -v jenkins-plugin-cli)" 2>/dev/null ] && [ $(version $(jenkins-plugin-cli --version)) -ge $(version "2.1.1") ]; then
      jenkins-plugin-cli --verbose --war "/usr/share/jenkins/jenkins.war" --plugin-file "/var/jenkins_home/plugins.txt" --latest true;
    else
      /usr/local/bin/install-plugins.sh `echo $(cat /var/jenkins_home/plugins.txt)`;
    fi
    echo "copy plugins to shared volume"
    yes n | cp -i /usr/share/jenkins/ref/plugins/* /var/jenkins_plugins/;

  plugins.txt: |-
    kubernetes:1.31.3
    workflow-aggregator:2.6
    git:4.10.2
    configuration-as-code:1.55.1