apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins-server.fullname" . }}
  labels:
    {{- include "jenkins-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jenkins-server.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins-server.fullname" . }}-agent
  labels:
    {{- include "jenkins-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
      protocol: TCP
      name: jnlp
  selector:
    {{- include "jenkins-server.selectorLabels" . | nindent 4 }}
