apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jenkins-server.fullname" . }}
  labels:
    {{- include "jenkins-server.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "jenkins-server.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jenkins-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jenkins-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jenkins-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: "install-plugins"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command:
        - 'sh'
        - '-c'
        - >
          rm -rfv /var/jenkins_home/lost+found;
          chmod -R 777 /var/jenkins_home;
          cp /var/jenkins_config/installPlugin.sh /var/jenkins_home/.;
          chmod +x /var/jenkins_home/installPlugin.sh;
          /var/jenkins_home/installPlugin.sh
        volumeMounts:
        - mountPath: "/var/jenkins_home"
          name: jenkins-home
        - mountPath: /var/jenkins_plugins
          name: plugin-dir
        - mountPath: /var/jenkins_config
          name: jenkins-config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-home
          - mountPath: /usr/share/jenkins/ref/plugins
            name: plugin-dir
            readOnly: false
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: agent
              containerPort: 50000
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /login
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /login
#              port: http
#            initialDelaySeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: {{ include "jenkins-server.fullname" . }}
      - name: plugin-dir
        emptyDir: {}
      - name: jenkins-config
        configMap:
          name: {{ template "jenkins-server.fullname" . }}